/**
 * EatAware Ingredient Knowledge Base
 * 28 ingredients with full health profiles
 */
export const INGREDIENTS = [
  {
    id: 'tbhq',
    name: 'TBHQ (INS 319)',
    aka: ['tert-Butylhydroquinone', 'Antioxidant 319'],
    concern: 'high',
    category: 'Synthetic Antioxidant',
    fssai: 'Permitted with limits',
    summary: 'Synthetic antioxidant used to extend shelf life of fried foods and instant noodles.',
    organs: ['liver', 'immune'],
    effects: {
      immediate: 'Nausea, tinnitus, and vomiting at high doses.',
      longterm: 'Animal studies link high doses to precancerous stomach lesions. IARC Group 3 — not classifiable as a carcinogen in humans at permitted levels.',
    },
    found_in: ['Instant noodles', 'Biscuits', 'Chips', 'Cookies', "Lay's", 'Maggi'],
    safer: 'Products using tocopherols (Vitamin E) as antioxidant instead.',
    source: 'FSSAI Food Safety Standards; IARC Monographs',
  },
  {
    id: 'tartrazine',
    name: 'Tartrazine (E102)',
    aka: ['INS 102', 'FD&C Yellow No. 5', 'Acid Yellow 23'],
    concern: 'high',
    category: 'Synthetic Colour',
    fssai: 'Permitted in beverages and confectionery',
    summary: 'Bright yellow azo dye widely used in Indian snacks, beverages, and sweets.',
    organs: ['brain', 'immune'],
    effects: {
      immediate: 'Triggers hyperactivity in sensitive children. Allergic reactions in aspirin-sensitive individuals.',
      longterm: 'UK Food Standards Agency study linked tartrazine to increased hyperactivity in children. Banned in Norway and Austria.',
    },
    found_in: ['Lemon drinks', 'Coloured sweets', 'Chips', 'Instant soups', 'Pickles'],
    safer: 'Products coloured with turmeric (E100) or annatto.',
    source: 'UK FSA McCann study (2007); FSSAI',
  },
  {
    id: 'msg',
    name: 'MSG (INS 621)',
    aka: ['Monosodium Glutamate', 'Ajinomoto', 'Umami seasoning'],
    concern: 'caution',
    category: 'Flavour Enhancer',
    fssai: 'Permitted — GRAS status in most countries',
    summary: 'Sodium salt of glutamic acid. Amplifies savoury flavour. Generally recognised as safe at normal dietary levels.',
    organs: ['brain'],
    effects: {
      immediate: '"Chinese Restaurant Syndrome" — headache, flushing — reported in sensitive individuals but not confirmed in double-blind trials.',
      longterm: 'High doses in animal studies caused brain lesions, but human dietary intake is far lower. No consensus harm at culinary amounts.',
    },
    found_in: ['Instant noodles', 'Chips', 'Namkeen', 'Processed soups', 'Fast food'],
    safer: 'Products with no added MSG; natural umami from tomatoes, mushrooms.',
    source: 'FDA GRAS list; WHO Food Additives guidelines',
  },
  {
    id: 'palm_oil',
    name: 'Palm Oil / Palmolein',
    aka: ['RBD Palmolein', 'Vegetable oil (palm)', 'Palm fat'],
    concern: 'caution',
    category: 'Saturated Fat',
    fssai: 'Permitted — widely used',
    summary: 'Cheapest edible oil globally. High in saturated fat (~50%). Environmental concern: deforestation.',
    organs: ['heart', 'liver'],
    effects: {
      immediate: 'No acute effects.',
      longterm: 'High saturated fat associated with raised LDL cholesterol. Regular high intake linked to increased cardiovascular risk. Contains glycidyl fatty acid esters (GE) from refining — possible carcinogen.',
    },
    found_in: ['Biscuits', 'Chips', 'Instant noodles', 'Margarine', 'Chocolate spreads'],
    safer: 'Products using cold-pressed mustard, sunflower, or olive oil.',
    source: 'WHO dietary fat guidelines; EFSA palm oil safety assessment (2016)',
  },
  {
    id: 'maida',
    name: 'Refined Flour (Maida)',
    aka: ['Refined wheat flour', 'White flour', 'All-purpose flour'],
    concern: 'caution',
    category: 'Refined Grain',
    fssai: 'Permitted',
    summary: 'Wheat stripped of bran and germ. High glycaemic index (~70). Low in fibre and nutrients.',
    organs: ['gut', 'pancreas'],
    effects: {
      immediate: 'Rapid blood sugar spike followed by crash. Promotes overeating.',
      longterm: 'Regular consumption associated with increased Type 2 diabetes risk, obesity, and gut dysbiosis due to lack of fibre.',
    },
    found_in: ['Bread', 'Biscuits', 'Namkeen', 'Instant noodles', 'Pasta', 'Pizza bases'],
    safer: 'Products using whole wheat atta, ragi, or jowar flour.',
    source: 'Glycaemic Index database; ICMR dietary guidelines',
  },
  {
    id: 'maltodextrin',
    name: 'Maltodextrin',
    aka: ['Modified starch', 'Glucose polymer'],
    concern: 'caution',
    category: 'Refined Carbohydrate',
    fssai: 'Permitted',
    summary: 'Processed starch from corn or wheat. GI of 110 — higher than table sugar (GI 65).',
    organs: ['pancreas', 'gut'],
    effects: {
      immediate: 'Rapid blood sugar spike — faster than sugar itself.',
      longterm: 'May alter gut microbiome by promoting pathogenic bacteria. Associated with insulin resistance with frequent consumption.',
    },
    found_in: ['Protein powders', 'Energy drinks', 'Infant formula', 'Sauces', 'Low-fat products'],
    safer: 'Products using whole food ingredients or resistant starch.',
    source: 'Glycaemic Index Research Institute; Gut microbiome studies',
  },
  {
    id: 'sodium_benzoate',
    name: 'Sodium Benzoate (INS 211)',
    aka: ['E211', 'Benzoate of soda'],
    concern: 'high',
    category: 'Preservative',
    fssai: 'Permitted in acidic foods',
    summary: 'Common preservative. Reacts with Vitamin C to form benzene — a known carcinogen.',
    organs: ['liver', 'brain'],
    effects: {
      immediate: 'Linked to hyperactivity in children (McCann study). Allergic reactions in sensitive individuals.',
      longterm: 'Benzene formation in Vitamin C-containing products is a concern. IARC classifies benzene as Group 1 carcinogen.',
    },
    found_in: ['Soft drinks', 'Fruit juices', 'Pickles', 'Sauces', 'Salad dressings'],
    safer: 'Products preserved with citric acid or rosemary extract.',
    source: 'UK FSA; FDA benzene in beverages study; IARC Group 1',
  },
  {
    id: 'sunset_yellow',
    name: 'Sunset Yellow (E110)',
    aka: ['INS 110', 'FD&C Yellow No. 6', 'Orange Yellow S'],
    concern: 'high',
    category: 'Synthetic Colour',
    fssai: 'Permitted in beverages',
    summary: 'Orange-yellow azo dye. Part of the "Southampton Six" colours linked to hyperactivity.',
    organs: ['immune', 'brain'],
    effects: {
      immediate: 'Allergic reactions, especially in aspirin-sensitive people. Part of the UK FSA hyperactivity study.',
      longterm: 'Possible association with hyperactivity in children. Banned or restricted in several countries.',
    },
    found_in: ['Orange drinks', 'Sauces', 'Jelly', 'Sweets', 'Chips'],
    safer: 'Products using annatto (E160b) or beta-carotene for orange colour.',
    source: 'UK FSA McCann study (2007); EFSA re-evaluation',
  },
  {
    id: 'caramel_colour',
    name: 'Caramel Colour (E150d)',
    aka: ['Ammonia sulfite caramel', 'INS 150d'],
    concern: 'caution',
    category: 'Synthetic Colour',
    fssai: 'Permitted',
    summary: 'Made by heating sugar with ammonia and sulfites. Class IV caramel. Contains 4-MEI — a possible carcinogen.',
    organs: ['liver'],
    effects: {
      immediate: 'No acute effects at dietary levels.',
      longterm: '4-MEI (a byproduct) classified as IARC Group 2B — possibly carcinogenic to humans.',
    },
    found_in: ['Colas', 'Soy sauce', 'Gravies', 'Beer', 'Bread'],
    safer: 'Products using Class I plain caramel (no ammonia) or natural colouring.',
    source: 'IARC Monograph 101 (2012) — 4-methylimidazole',
  },
  {
    id: 'trans_fat',
    name: 'Trans Fat (PHO)',
    aka: ['Partially hydrogenated oil', 'Vanaspati', 'Dalda'],
    concern: 'high',
    category: 'Industrial Fat',
    fssai: 'Limit: ≤2% from Jan 2022',
    summary: 'Industrially produced by partially hydrogenating vegetable oil. Worst dietary fat for cardiovascular health.',
    organs: ['heart', 'liver'],
    effects: {
      immediate: 'No acute effect.',
      longterm: 'Raises LDL, lowers HDL simultaneously — double cardiovascular harm. WHO estimates 500,000 premature deaths annually from trans fat. No safe level of consumption.',
    },
    found_in: ['Vanaspati', 'Margarine', 'Bakery products', 'Street food', 'Some biscuits'],
    safer: 'Products that explicitly state "0g trans fat" and use non-hydrogenated oils.',
    source: 'WHO REPLACE initiative; FSSAI trans fat regulation 2021',
  },
  {
    id: 'lactobacillus',
    name: 'Lactobacillus (Probiotics)',
    aka: ['Live cultures', 'Active cultures', 'Probiotic bacteria'],
    concern: 'safe',
    category: 'Probiotic',
    fssai: 'Permitted — beneficial',
    summary: 'Beneficial bacteria that support gut health. Found in fermented dairy products.',
    organs: ['gut', 'immune'],
    effects: {
      immediate: 'Improves digestion, reduces bloating. May cause mild gas initially.',
      longterm: 'Improves gut microbiome diversity. Linked to better immune function, mood regulation, and reduced diarrhoea risk.',
    },
    found_in: ['Yoghurt', 'Yakult', 'Curd', 'Lassi', 'Some probiotic drinks'],
    safer: null,
    source: 'WHO/FAO Probiotic guidelines; systematic reviews in Lancet',
  },
  {
    id: 'whole_grain',
    name: 'Whole Grain / Millets',
    aka: ['Ragi', 'Bajra', 'Jowar', 'Whole wheat', 'Rolled oats', 'Foxtail millet'],
    concern: 'safe',
    category: 'Complex Carbohydrate',
    fssai: 'Permitted — recommended',
    summary: 'Contains all three parts of the grain — bran, germ, endosperm. High fibre, vitamins, minerals.',
    organs: ['gut', 'heart', 'pancreas'],
    effects: {
      immediate: 'Slower digestion. More sustained energy than refined grains.',
      longterm: 'Reduces risk of Type 2 diabetes by 20-30%. Associated with lower cardiovascular risk and improved gut microbiome.',
    },
    found_in: ['Saffola Oats', 'Ragi biscuits', 'Jowar-based snacks', 'Multigrain bread'],
    safer: null,
    source: 'ICMR dietary guidelines; Harvard T.H. Chan School of Public Health',
  },
  {
    id: 'phosphoric_acid',
    name: 'Phosphoric Acid (E338)',
    aka: ['INS 338', 'Acidity regulator 338'],
    concern: 'caution',
    category: 'Acidity Regulator',
    fssai: 'Permitted in beverages',
    summary: 'Gives colas their sharp taste. Acidic — erodes tooth enamel and may leach calcium from bones.',
    organs: ['bones', 'teeth', 'kidneys'],
    effects: {
      immediate: 'Erodes tooth enamel on contact.',
      longterm: 'Associated with lower bone mineral density with daily consumption. May contribute to kidney stones.',
    },
    found_in: ['Coca-Cola', 'Pepsi', 'Diet sodas', 'Some energy drinks'],
    safer: 'Citric acid-based drinks; plain water; coconut water.',
    source: 'American Journal of Clinical Nutrition; Harvard Nurses Health Study',
  },
  {
    id: 'added_sugar',
    name: 'Added Sugar',
    aka: ['Sucrose', 'Cane sugar', 'Sugar syrup', 'Dextrose', 'Glucose syrup'],
    concern: 'caution',
    category: 'Refined Sugar',
    fssai: 'Permitted — limit recommended',
    summary: 'Sugar added during processing. WHO recommends <25g/day (6 teaspoons). Indian average is 3–4× this.',
    organs: ['liver', 'pancreas', 'teeth'],
    effects: {
      immediate: 'Blood sugar spike, energy crash, promotes overeating.',
      longterm: 'Associated with obesity, Type 2 diabetes, fatty liver, dental caries, and cardiovascular disease.',
    },
    found_in: ['Soft drinks', 'Biscuits', 'Chocolates', 'Fruit juices', 'Cereals'],
    safer: 'Products sweetened with dates, jaggery, or no added sweeteners.',
    source: 'WHO sugar guidelines 2015; ICMR-NIN dietary guidelines',
  },
]

export const CONCERN_LABELS = {
  high:    { label: 'High Concern',  color: '#dc2626', bg: '#fef2f2', emoji: '🔴' },
  caution: { label: 'Caution',       color: '#d97706', bg: '#fffbeb', emoji: '🟡' },
  safe:    { label: 'Beneficial',    color: '#16a34a', bg: '#f0fdf4', emoji: '🟢' },
}

export const ORGAN_ICONS = {
  heart:    '❤️',
  liver:    '🫁',
  brain:    '🧠',
  gut:      '🦠',
  immune:   '🛡️',
  pancreas: '🩺',
  bones:    '🦴',
  teeth:    '🦷',
  kidneys:  '🫘',
}
